version: "2"

services:
  # nats:
  #   image: 'nats:0.8.0'
  #   entrypoint: "/gnatsd -DV"
  #   expose:
  #     - "4222"
  #   ports:
  #     - "8222:8222"
  #   hostname: nats-server
  mapmatcher:
    container_name: iosl_spring_map_matcher
    environment:
      - "NATS_URI=http://localhost:8222"
    build:
      context: ./MapMatcher/
      dockerfile : Dockerfile
    volumes:
      - ./MapMatcher/target:/target
      - ./MapMatcher/data:/data
 # pollutionmatcher:
 #   container_name: iosl_spring_pollution_matcher
 #   environment:
 #     - "NATS_URI=nats://nats:IoslProject2018@iosl2018hxqma76gup7si-vm0.westeurope.cloudapp.azure.com:4222"
 #   build:
 #     context: ./PollutionMatcher/
 #     dockerfile : Dockerfile
 #   volumes:
 #     - ./PollutionMatcher/target:/target
  # osrm-server: 
  #   image: osrm/osrm-backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.osrm
  #   ports:
  #     - 5000:5000
  #   command: bash -c "osrm-routed --algorithm mld berlin-latest.osrm"
  #toll-simulator:
  #  build:
  #    context: ./toll-simulator-master
  #  image: toll-simulator
  #  ports:
  #    - "3001:3000"
  #  environment:
  #    PORT: 3000
  #    NATS_URL: nats://nats-server:4222
  nats-server:
    container_name: nats-server
    hostname: nats-server
    image: 'nats:0.8.0'
    entrypoint: "/gnatsd -m 8222"
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
  #  healthcheck:
  #    test: ["CMD", "curl", "-f", "http://localhost:8222/api/status"]
  #    interval: 5s
  #    timeout: 3s
  #    retries: 10

  toll-simulator:
    container_name: toll-simulator
    build:
      context: toll/toll-simulator/
    image: toll-simulator
    ports:
      - 8760:8760
    environment:
      PORT: 8760
      NATS_URL: nats://localhost:4222
   # healthcheck:
   #   test: ["CMD", "curl", "-f", "http://localhost:8760/api/status"]
   #   interval: 5s
   #   timeout: 3s
   #   retries: 10
   # depends_on:
   #   - nats-server

  poll-dashboard:
    container_name: poll-dashbaord
    build:
      context: toll/poll-dashboard/
    image: poll-dashboard
    ports:
      - 80:4000
    environment:
      NATS_URL: nats://localhost:4222
   # healthcheck:
   #   test: ["CMD", "curl", "-f", "http://localhost:4000/"]
   #   interval: 5s
   #   timeout: 3s
   #   retries: 10
   # depends_on:
   #   - nats-server
   #   - scope
   #   - toll-simulator

  scope:
    container_name: scope
    image: weaveworks/scope:1.10.1
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
  

  # ----------------- notes --------------------------------
  # have 2 docker compose files (one for our project specific and one for all projects)
  # decide if database is in or out
  # 19 december : convince people, show something
  # find a tool for nats printing
  # write documentation !
  # mongo db for buffering
  # implémenter client web nodejs visualisation chaque queue de nats
  # outil polygone postgis
