version: "3.0"

services:

  nats-server:
    container_name: nats-server
    hostname: nats-server
    image: 'nats:0.8.0'
    entrypoint: "/gnatsd -m 8222"
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/api/status"]
      interval: 5s
      timeout: 3s
      retries: 10

  toll-simulator:
    container_name: toll-simulator
    build:
      context: toll-simulator/
    image: toll-simulator
    ports:
      - 8760:8760
    environment:
      PORT: 8760
      NATS_URL: nats://nats-server:4222
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8760/api/status"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      - nats-server

  poll-dashboard:
    container_name: poll-dashbaord
    build:
      context: poll-dashboard/
    image: poll-dashboard
    ports:
      - 80:4000
    environment:
      NATS_URL: nats://nats-server:4222
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      - nats-server
      - scope
      - toll-simulator

  scope:
    container_name: scope
    image: weaveworks/scope:1.10.1
    network_mode: "host"
    pid: "host"
    privileged: true
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"